// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TaskManagerV1HTTPClient is an autogenerated mock type for the TaskManagerV1HTTPClient type
type TaskManagerV1HTTPClient struct {
	mock.Mock
}

// Health provides a mock function with given fields: ctx
func (_m *TaskManagerV1HTTPClient) Health(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskManagerV1HTTPClient creates a new instance of TaskManagerV1HTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskManagerV1HTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskManagerV1HTTPClient {
	mock := &TaskManagerV1HTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
