// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/sergicanet9/go-microservices-demo/health-api/core/models"
	mock "github.com/stretchr/testify/mock"
)

// HealthService is an autogenerated mock type for the HealthService type
type HealthService struct {
	mock.Mock
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *HealthService) HealthCheck(ctx context.Context) ([]models.HealthResp, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 []models.HealthResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.HealthResp, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.HealthResp); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.HealthResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHealthService creates a new instance of HealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthService {
	mock := &HealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
