basePath: /health-api/v1
definitions:
  models.HealthResp:
    properties:
      error:
        type: string
      service_url:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: Powered by scv-go-tools - https://github.com/sergicanet9/scv-go-tools
  title: Health API
  version: v1
paths:
  /health:
    get:
      description: Returns the status of all the microservices in the system
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.HealthResp'
            type: array
      summary: Health check
      tags:
      - Health
swagger: "2.0"
