name: test
on: 
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Run all unit tests
        run: make all-test-unit

  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Start services
        run: make up
      - name: Run all integration tests
        run: make test-integration
      - name: Wait for services to be ready
        run: sleep 10
      - name: Stop services
        if: always()
        run: make down