name: test
on: 
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Run all unit tests
        run: make all-test-unit

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Start services
        run: make up

      - name: Wait for services to be ready
        run: |
          for i in $(seq 1 30); do
            echo "Waiting for services to be ready... (attempt $i/30)"
            if curl -sS http://localhost:82/health-api/v1/health &>/dev/null; then
              echo "healthcheck successful"
              break
            fi
            sleep 5
          done

      - name: Run e2e tests
        run: make test-e2e

      - name: Stop services
        if: always()
        run: |
          make down
          docker system prune -a -f