name: test
on: 
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arnested/go-version-action@v1
        id: go-version
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.minimal }}
      - name: Run all unit tests
        run: make all-test-unit

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v3
      - uses: arnested/go-version-action@v1
        id: go-version
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.minimal }}
      - name: Run all integration tests
        run: make test-integration
